## Operations

### Indexing & Slicing

In [2]:
import numpy as np

In [3]:
arr = np.array([10, 20, 30, 40, 50])

In [4]:
print(arr[0])

10


In [16]:
print(arr[1:])

[20 30 40 50]


In [14]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

#### 2D Indexing

In [ ]:
print(matrix[2, 4])

#### 2D Slicing

In [20]:
print(matrix[1, :])

[5 6 7 8]


In [23]:
print(matrix[:, 1:3])

[[ 2  3]
 [ 6  7]
 [10 11]]


In [24]:
print(matrix[0:2, 1:3])

[[2 3]
 [6 7]]


In [25]:
print(matrix[::2, ::2])

[[ 1  3]
 [ 9 11]]


In [27]:
print(matrix[:, -1])

[ 4  8 12]


In [ ]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

## Mathematical Operation

In [28]:
arr = np.array([1, 2, 3])

In [29]:
print(arr + 10)

[11 12 13]


In [30]:
print(arr * 2) 

[2 4 6]


In [31]:
print(arr ** 2)

[1 4 9]


### built-in functions

In [32]:
print(arr.mean())
print(arr.sum())
print(arr.max())
print(arr.min())

2.0
6
3
1


## Matrix Operations

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [ ]:
print(a + b)

[[ 6  8]
 [10 12]]


In [ ]:
print(a * b)  # Element-wise multiplication

[[ 5 12]
 [21 32]]


In [ ]:
print(np.dot(a, b)) # Normal matrix multiplication

[[19 22]
 [43 50]]
