# Numpy

## What is numpy
Numpy = Numerical Python

- mathematical operations
- multi-dimensional array
- scientific computiong

In [ ]:
import numpy as np

## Numpy Arrays vs Python Lists

In [6]:
# Python Lists
my_list = [1, 2, 3, 4, 5]

# Numpy Arrays
my_array = np.array([1, 2, 3, 4, 5])

print("Python List:", my_list)
print("Numpy Array:", my_array)

Python List: [1, 2, 3, 4, 5]
Numpy Array: [1 2 3 4 5]


In [7]:
print(my_array * 2)

[ 2  4  6  8 10]


In [8]:
print(my_list * 2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


## Create Numpy Array

In [ ]:
np.zeros(5)
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones(5)
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
np.arange(0, 10)
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [22]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## Array shape and Reshape

### Shape = Structure of array

it tells us
- how many rows
- how many columns

In [26]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.shape)

(5,)


In [ ]:
arr2 = np.array([[1, 2, 3], 
                 [4, 5, 6]])
print(arr2.shape)

(2, 3)


In [31]:
arr3 = np.zeros((2, 3, 4))
print(arr3.shape)

(2, 3, 4)


### What is Reshape
Reshape = Chnage structure without changing data

In [32]:
arr = np.arange(6)
print(arr)

[0 1 2 3 4 5]


In [37]:
arr2 = arr.reshape((2, 3))
print(arr2)

[[0 1 2]
 [3 4 5]]


In [49]:
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [50]:
arr2 = arr.reshape((3, -1))
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
arr.ndim
arr.size
arr.shape
arr.reshape()

2

In [56]:
arr = np.arange(8).reshape((2, 4))

print(arr.ndim)
print(arr.size)
print(arr.shape)

2
8
(2, 4)
